# Generated by Django 5.2.4 on 2025-07-23 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Đã mất'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Chọn thể loại cho cuốn sách này', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 ký tự <a href="https://www.isbn-international.org/content/what-isbn">mã số ISBN</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Nhập mô tả ngắn gọn cho cuốn sách', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID duy nhất cho cuốn sách này trong toàn bộ thư viện', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Bảo trì'), ('o', 'Đang được mượn'), ('a', 'Sẵn có'), ('r', 'Đã được đặt trước')], default='m', help_text='Tình trạng sách', max_length=1),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Nhập thể loại sách (ví dụ: Khoa học viễn tưởng)', max_length=200),
        ),
    ]
